POST http://localhost:3000/api/short-links/
Content-Type: application/json

{
  "title": "codeit2",
  "url": "https://codeit.kr"
}

###

GET http://localhost:3000/api/short-links/65dec0a3d21658914c57ce79

###

GET http://localhost:3000/api/short-links/

###

PATCH http://localhost:3000/api/short-links/65dec0a3d21658914c57ce79
Content-Type: application/json

{
  "title": "codeit-edit-1"
}

###

DELETE  http://localhost:3000/api/short-links/65dec235d21658914c57ce7d